project:
  type:
    website:
      navbar:
        background: primary
        search: true
        left:
          - eda.qmd
          - model.qmd 
  execute-dir: project

format:
  html:
    toc: true